import { ChanelBar } from "./ChanelBar/ChanelBar"

const chanelData = [{"id":1,"nameChanel":"Eye Wash","descriptionChanel":"varius integer ac leo","is_audio":true},
{"id":2,"nameChanel":"SOTALOL ","descriptionChanel":"sapien in sapien iaculis congue","is_audio":true},
{"id":3,"nameChanel":"Imipramine ","descriptionChanel":"morbi porttitor lorem id ligula","is_audio":true},
{"id":4,"nameChanel":"Treatment Set","descriptionChanel":"tellus in","is_audio":false},
{"id":5,"nameChanel":"Methocarbamol","descriptionChanel":"ligula in lacus curabitur at","is_audio":true},
{"id":6,"nameChanel":"Methimazole","descriptionChanel":"commodo placerat praesent blandit nam","is_audio":true},
{"id":7,"nameChanel":"Levothyroxine","descriptionChanel":"luctus et ultrices posuere","is_audio":false},
{"id":8,"nameChanel":"Superlightener","descriptionChanel":"dui vel nisl","is_audio":true},
{"id":9,"nameChanel":"Prevantics","descriptionChanel":"dui nec","is_audio":true},
{"id":10,"nameChanel":"GIM","descriptionChanel":"at vulputate","is_audio":false},
{"id":11,"nameChanel":"Valsartan","descriptionChanel":"leo odio porttitor id","is_audio":false},
{"id":12,"nameChanel":"ISOVUE","descriptionChanel":"ipsum dolor sit amet","is_audio":true},
{"id":13,"nameChanel":"Quetiapine fumarate","descriptionChanel":"amet cursus id turpis integer","is_audio":true},
{"id":14,"nameChanel":"Propranolol ","descriptionChanel":"massa tempor convallis nulla","is_audio":true},
{"id":15,"nameChanel":"Risperidone","descriptionChanel":"urna ut tellus nulla","is_audio":false},
{"id":16,"nameChanel":"MedActive Patient Friendly","descriptionChanel":"eros suspendisse accumsan","is_audio":true},
{"id":17,"nameChanel":"Bladder Kidney","descriptionChanel":"rutrum neque aenean auctor gravida","is_audio":true},
{"id":18,"nameChanel":"Coffea cruda","descriptionChanel":"non quam","is_audio":true},
{"id":19,"nameChanel":"Warfarin Sodium","descriptionChanel":"nibh in","is_audio":true},
{"id":20,"nameChanel":"Close Up","descriptionChanel":"sapien a","is_audio":true},
{"id":21,"nameChanel":"One Seed","descriptionChanel":"quisque erat","is_audio":false},
{"id":22,"nameChanel":"DayRelief","descriptionChanel":"sed lacus morbi sem mauris","is_audio":false},
{"id":23,"nameChanel":"Hydrocortisone","descriptionChanel":"penatibus et magnis dis","is_audio":true},
{"id":24,"nameChanel":"Gelato APF","descriptionChanel":"et magnis","is_audio":false},
{"id":25,"nameChanel":"Pioglitazone ","descriptionChanel":"sem duis aliquam convallis","is_audio":false},
{"id":26,"nameChanel":"Oxcarbazepine","descriptionChanel":"elit ac nulla sed vel","is_audio":false},
{"id":27,"nameChanel":"Standardized","descriptionChanel":"donec quis","is_audio":true},
{"id":28,"nameChanel":"Sertraline ","descriptionChanel":"suspendisse potenti cras in","is_audio":true},
{"id":29,"nameChanel":"LISINOPRIL","descriptionChanel":"consequat lectus in","is_audio":true},
{"id":30,"nameChanel":"Lunesta","descriptionChanel":"in hac","is_audio":false}]
export default chanelData